### ISSUE TITLE
As a user whose account has been deactivated, I need to know why I can't log in to SE so that I can find out how to regain access

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#90]
If the user does have an account but the account is not active ("Active" is unchecked), they get a 405 error:
![image](https://user-images.githubusercontent.com/31591389/51629186-eb5c1c00-1f14-11e9-80c3-0b1e1842fd3b.png)

(FWIW, if the user had an account, was deactivated and getting the 405 error, and then has their account fully deleted, it does go back to just giving them "Permission denied" 403 error--tested this with my sponsored account)

Give them same message they get with 403 error.

**Comment by mfldavidson** [comment]
Ok so I am not positive (be gentle, I'm inexperienced) but I think that we would need to add in logic that doesn't already exist to use this new template or use the 403.html template (I would want it to be the exact same, so if possible, using the 403.html template would be ideal). The reason I'm thinking this is because [this resource on Django](https://docs.djangoproject.com/en/2.1/ref/views/) seems to be saying that the error views that we have now are all sort-of default, and automatically point to the appropriate template name. However, there isn't a built in one for a 405 error.

@jonespm @zqian when you have time, would you mind advising on this?

The actual messages that are displaying are coming from the following code in [index.html lines 117-129](https://github.com/tl-its-umich-edu/student_explorer/blob/develop/student_explorer/templates/student_explorer/index.html):

```
        <div class="container-index">
            {% if messages %}
                <div class="container alert-message">
                    {% for message in messages %}
                        <div class='alert alert-{{ message.tags }} alert-dismissible' role='alert'>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
```

**Comment by jonespm** [comment]
Yeah dealing with the 405 will take more work. Looks like maybe this solution I can look at getting that to work, just provide the template! (Can just call it 405.html in that same folder)

https://stackoverflow.com/a/4634795/3708872

**Comment by jonespm** [comment]
@mfldavidson I committed your html file and made the middleware change live on dev. Looks like it's working to me, can you test it? I'll work on a PR for it.

**Comment by mfldavidson** [comment]
Testing in dev. I'm getting stuck as I try to log in. Admin console is recording that the user logged in but I'm not getting properly redirected. I'll send the video to you in another channel in case it's a security issue.

**Comment by mfldavidson** [comment]
To recap convo we just had in person: testing new fix has gone pretty well, but still encountering these issues:
- Takes too long to redirect user/load page
- Any attempts to redirect several times (either reloading page a bunch or clicking around on things like "My Students" or search leads to getting stuck at https://shib-idp-test.www.umich.edu/idp/profile/SAML2/POST/SSO
- Clicking "login" after getting redirected to the error page gives the user the same "This page isn’t working If the problem continues, contact the site owner. HTTP ERROR 405" message that we are trying to fix with this issue.

**Comment by jonespm** [comment]
Some of that delay might be because of shibboleth test. Not sure how we can
tell but I'll see if I can think of something

I'll look at the login link after permission denied though. Thanks!

**Comment by jonespm** [comment]
I think I fixed your 3rd bullet point (and possibly second on dev) with a recent commit. Going to merge that PR so we can test it all.
